Parser refactor
azu/gitbook-plugin-include-codeblock pull request #43
Opened 2017-01-23 02:06 UTC by gdolle

Major refactoring for the parser. Breaking changes (3.1.0 ?)

Changelog

- Fix options bugs (random behaviour between book.json and local command, ace plugin does not support quotes in command options)
- Add Url support #42 (sync http request using [sync-request](https://www.npmjs.com/package/sync-request) modules + check url [valid-url](https://www.npmjs.com/package/valid-url))
- Refactor options using immutable maps (more robust). It makes easier future new options, see `src/options.js`
- Support real types (not retrocompatible for book options). For example `edit:true` instead of `edit:"true"`,  to be more consistent (this fix an ace plugin bug).
- Add parser checks for types.
- Add different warn level.
- `template`, `fixlang`, `lang`, `theme` are now also local/global options. We can set a template per code, a theme per code, etc.. or globally.
- Refactor test for these last changes.
- Add new tests for URL
- End support of `lang-typescript` to use uniform options `lang:"typescript"` to be consistent with other options and to simplify functions.
- Support multiple snippet codes. Now we can do `[import:"tag0,tag1,..."](fixtures/test.js)` to import several snippets into one codeblock , for example
```cpp
//! [tag0]
int a;
//! [tag0]
// A comment or a code
//! [tag1]
int b;
//! [tag1]
```
will produce
```cpp
int a;
int b;
```

It should work far better with this PR :)

I've been noticed that ace plugin might crash after a page reload in previous version, but I couldn't reproduce that problem. However, these changes fix some bugs and "might" be fix for that behaviour, we will see.

NB: It might be interesting to have a look to async operation in the future to optimize the code.

@azu waiting for your review, you'll have some work ;)

2017-01-23 09:34 UTC, azu commented
Oh, large diff.. 
I'll look it lator.
Can you separate refactor PR and feature PR if possible.

2017-01-23 13:10 UTC, gdolle commented on src/parser.js
> +export function getContent( filePath, originalPath )
Part of feature #42

2017-01-23 13:11 UTC, gdolle commented on templates/ace-template.hbs
> +{%ace edit={{edit}}, check={{check}}, theme="{{theme}}", lang="{{lang}}" %}
Major bug fix here

2017-01-23 13:15 UTC, gdolle commented
@azu Actually, features are minors and deeply dependent of the of refactor. It'd be quite difficult to separate now. 

Would it be ok to keep it as one PR ?

The related features changes are
- multiple markers (parseVariableFromLabel => change the regex to have several comma ~1line)
- URL parser ( getContent => load url or file ~5lines) 
+ the 1 tests for each in `test-parser.js`

(I added comments on file changes to help)

2017-01-24 11:35 UTC, azu commented
@gdolle fmm, I want to separate big PR to smll PRs by following reasons.

> Add Url support #42 (sync http request using sync-request modules + check url valid-url)

Sync request is simple solution, but it is not correct solution.
Because GitBook support async hook.

- https://toolchain.gitbook.com/plugins/hooks.html

(Not actuall code)
```js
// THIS IS IMAGINE
module.exports = {
    hooks: {
        "page:before": function(page) {
            var options = this.options.pluginsConfig["include-codeblock"];
            var pageDir = path.dirname(page.rawPath);
            var parseResults = parse(page.content, pageDir, options);
            var promises = results.map(result => {
                return requestUrlAndCreateReplaceContent(result).then(newContent => {
                     replaceContent(page, newContent);
                });
            });
            return Promise.all(promises); // GitBook support async by returing promise
        }
    }
};
```

and

[Immutable.js](https://facebook.github.io/immutable-js/ "Immutable") is overlarge for this project.
I recommened that use ES2015 [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map "Map") insteadof immutable.js.

-----

Of course, Welcome to [bugfix](https://github.com/azu/gitbook-plugin-include-codeblock/pull/43#discussion_r97314114), but the bugfix should not contains other feature.
I hesitate to merge the bugfix PR.

2017-01-24 13:41 UTC, gdolle commented
Does ES2015 Map guaranty const Map values ?

Actually refactor parser:
1. immutable Map for read only (more robust to my opinion) 
2. handle key-val types (boolean, string, number). The "bug fix" is a consequence of the parser refactor (maybe my single comment is error prone) it's not really a feature.

I agree for the url feature, it is from far not perfect. I'll separate it in another PR.

2017-01-25 09:10 UTC, azu reviewed
> Does ES2015 Map guaranty const Map values ?

Yes and No.

Immutable.js is great library, but it is not first class in JavaScript.
In other word, When other constributor see the code that includes immutable.js, they have to learn about immutable.js. I think that it contains cost.

I've written some Map examples.

If you actualy want to use immutable.js, I can't prevent it.

> I agree for the url feature, it is from far not perfect. I'll separate it in another PR.

Ok.

2017-01-25 09:10 UTC, azu commented on src/parser.js
> +    Object.keys(kv).forEach(key => {
Can ES2015 Map does same thing?

```js
const resultMap = new Map();
kvMap.forEach(key => { 
   // something
   resultMap.set(key, foo);
}
return resultMap;
```

2017-01-25 09:10 UTC, azu commented on src/parser.js
> +    const contextMap = kvMap.concat( immutable.Map({
`var mergedMap = new Map([...kvMap, ...otherMap])`

```js
var a = new Map([["k1", "v1"], ["k2", "v2"]]);
var b = new Map([["k3", "v3"], ["k4", "v4"]]);
var mergedMap = new Map([...a, ...b]);
console.log(mergedMap); // Map { k1: "v1", k2: "v2", k3: "v3", k4: "v4" }
```


```js
// Object to Map
new Map(Object.entries({ k : 1 }))
```

2017-01-25 09:13 UTC, azu commented
(Currently, this project mixed codeing style, We should apply ESLint  #39)

2017-01-29 19:56 UTC, gdolle commented
@azu I updated the code. 
- Remove immutable: I used object instead of Map and froze object that should be immutable. It should be understandable for future contributors.
- Remove URL feature.

I didn't apply yet Eslint, I'll have a look into that.

2017-01-30 00:07 UTC, gdolle commented
@azu I added eslint config following #39 and fix current code to the convention.
I also added a "check" script which test eslint on src/ and test/.
This script is executed in travis, therefore we can see if something is not good with respect to the coding style.
Let me know if it's ok for you like that. ;)

2017-02-01 00:48 UTC, azu requested changes
Thanks.
I've leave some comments

2017-02-01 00:48 UTC, azu commented on src/parser.js
> +}
Can you format indent or Run `$(npm bin)/eslint --fix src/ test/`?

2017-02-01 00:48 UTC, azu commented on src/parser.js
> +                    typeof defaultKeyValueMap[key] + "` unknown (see options.js)");
add `breaK;` to `default:` block.

2017-02-01 00:48 UTC, azu commented on src/parser.js
> +    if (unindent == true) {
use `===` insteadof `==`.

OR

```js
const unindent = kvm.unindent !== undefined ? kvm.unindent : false;
...
if (unindent) { ... }
...
```

2017-02-01 00:48 UTC, azu commented on package.json
> +  "version": "3.1.0",
PR is not include bump version.

2017-02-01 00:48 UTC, azu commented on package.json
>      "watch": "babel src --out-dir lib --watch --source-maps",
Maybe, `lint` command is meaningful.

Also, To define `"lint:fix": "eslint --fix src/*.js test/*.js"` is useful.

2017-02-09 09:46 UTC, gdolle commented on src/parser.js
> +}
weird eslint does not fix this lines..

2017-02-09 09:47 UTC, gdolle commented
Sorry for the late reply. I updated the code relatively to your last review

2017-02-10 11:15 UTC, azu approved these changes

2017-02-10 11:16 UTC, merged

2017-02-10 11:16 UTC, azu commented
@gdolle Thanks for great work!